config/routes.rb
Rails.application.routes.draw do
  require 'api'
  mount Shopshow::API => "/"
  require 'uszcn_api'
  mount Shopshow::Uszcn => '/'

  root to: 'welcome#index'
  post 'update_avatar', to: 'welcome#update_avatar'
  post 'update_recipient', to: 'welcome#update_recipient'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 手机客户端
  namespace :mobile do
    resources :users, only: [:new, :create, :show] do
      collection do
        post :send_code
        post :verify_code
        post :check_name
        get :regist_succeed
      end
    end

    scope :shopping_cart do
      get :goods, to: 'shopping_cart#goods'
      post :update_item, to: 'shopping_cart#update_item'
      post :remove, to: 'shopping_cart#remove'
      post :remove_selected, to: 'shopping_cart#remove_selected'
      get :confirm, to: 'shopping_cart#confirm'
    end
    get :orders, to: 'orders#index'
    post :orders, to: 'orders#index'
    
    resources :orders do 
      post :outbound_msg
    end
    

  end  
  post '/mobile/orders/handle_alipay_notify' => 'mobile/orders#handle_alipay_notify'
  
  scope :jabber do
    post :prebind, to: 'jabber#prebind'
  end

  # 买手后台系统
  namespace :delivery do
    root to: 'index#dashboard'

    get 'login', to: 'sessions#new', as: 'login'    
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :materials, only: [:create]

    resources :inbounds do
      member do
        get :query
      end
    end

    resources :orders do
      member do
        post :outbound       
        post :check_prepare_products 
        post :notify_carriage
        post :notify_tax        
      end
    end

    resources :outbounds do 
      member do
        get :query                        
      end                
    end

    resources :live_shows do
      member do        
        get :open
        get :close
        post :clearing_price
        get :shopping_list        
      end

      resources :products, shallow: true
      resources :messages, shallow: true
    end
  end

  get 'costco' => 'delivery/live_shows#preview_page'  
  get 'fresh' => 'delivery/live_shows#fresh_page'
    
  # 运维后台
  namespace :cpanel do
    root to: 'live_shows#index'

    scope :faqs do
      get '1' => 'faqs#faq1'      
      get '2' => 'faqs#faq2'      
      get '3' => 'faqs#faq3'      
    end

    scope :trailer do
      get 'costco' => 'trailers#costco'      
      get 'next' => 'trailers#next'
    end

    resources :live_shows do
      member do
        get :products
        post :products
        get :close        
      end
      get :choose_material
    end

    resources :users

    resources :products do
      member do
        post :publish
      end
    end

    resources :materials, only: [:create]

    resources :orders do
      resources :items, only: [:index]
    end
  end
end

app/controllers/cpanel/live_shows_controller.rb
class Cpanel::LiveShowsController < Cpanel::ApplicationController
  skip_before_action :login_required, only: :orders
  skip_before_action :admin_required, only: :orders
  before_action :find_live_show, only: [:show, :products, :orders, :edit, :update, :close]

  def index
    @live_shows = LiveShow.order('created_at DESC')
  end

  def show  
    @products = @live_show.products.order('created_at DESC')
    
    @orders = @live_show.orders.order('created_at DESC, user_id DESC').includes(:user).includes(:order_items)  

    @order_items = @live_show.order_items.select("*, sum(quantity) as quantity").joins(:order).where('orders.status = 3').group("order_items.sku_id")
  end

  def products
    @products = @live_show.products.order('created_at DESC')
    render layout: false
  end

  def new
    @live_show = LiveShow.new
  end

  def create
    @live_show = LiveShow.new live_show_params
    @live_show.generate_secure_id!
    @live_show.user_id = current_user.id

    if @live_show.save
      redirect_to cpanel_live_shows_path
    else
      render :new
    end
  end

  def edit        
  end

  def update
    @live_show.update_attributes(live_show_params)
    redirect_to cpanel_live_shows_path
  end

  def close
    @live_show.update_attributes!({ :closed => true })
    redirect_to cpanel_live_shows_path
  end

  def choose_material
    @materials = Material.where(live_show_id: params[:live_show_id])
                         .where(material_type: %w(jpeg jpg png gif))   
    render :layout => false
  end
  
  private

  def find_live_show
    @live_show = LiveShow.find params[:id]
  end

  def live_show_params
    params.require(:live_show).permit(
      :subject, :description, :preview, 
      :start_time, :close_time,
      :html_url,
      :countdown, :exchage_rate
    )
  end
end

app/controllers/delivery/application_controller.rb
class Delivery::ApplicationController < ActionController::Base
  layout 'delivery'
  helper_method :admin_login?, :current_admin

  private

  class AdminAccessDenied < Exception; end

  def admin_required
    unless admin_login?
      flash[:warning] = "请先登录"
      redirect_to delivery_login_path
    end    
  end

  def admin_login?
    !!current_admin
  end

  def current_admin
    @current_admin ||= login_from_session unless defined?(@current_admin)
    @current_admin
  end

  def login_as(admin)
    session[:admin_id] = admin.id
    @current_admin = admin
  end

  def logout
    session.delete :admin_id
    @current_admin = nil
  end

  def login_from_session
    return nil if session[:admin_id].blank?
    begin
      User.find(session[:admin_id]) 
    rescue
      session[:admin_id] = nil
    end 
  end

  def no_login_required
    if admin_login?
      redirect_to delivery_root_url
    end
  end  
end

app/controllers/delivery/inbounds_controller.rb
class Delivery::InboundsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show, only: [:new]
  before_action :find_inbound, only: [:show, :query]

  def index
    @inbounds = Inbound.order('created_at DESC')
  end

  def show
    @inbound_skus = @inbound.inbound_skus.includes(:sku, :inbound).order('created_at DESC')
  end

  def new
    @live_shows = LiveShow.all
    if @live_show.present?
      @products = @live_show.products.order('created_at DESC')
      @orders = @live_show.orders.order('created_at DESC, user_id DESC').includes(:user, :order_items)  
      @order_items = @live_show.order_items
                               .select("*, sum(quantity) as quantity")
                               .joins(:order)
                               .includes(:sku, :product)
                               .where('orders.status = ?', Order.statuses[:paid])
                               .group("order_items.sku_id")
    end
  end

  def create
    ActiveRecord::Base.transaction do
      channel = Channel.default
      inbound = channel.inbounds.build
      inbound.status = 0
      inbound.live_show_id = params[:live_show_id]
      inbound.save!

      skus = params[:skus]
      skus.each do |k, v|
        i_s = inbound.inbound_skus.build      
        i_s.sku_id = v[:sku_id]
        i_s.quantity = v[:amount].to_i
        i_s.save!
      end

      inbounded = skus.values.sum { |h| h[:amount].to_i }
      inbound.update_attributes!(:quantity => inbounded)
      inbound.notify_channel_inbound
    end

    render json: { success: true }
  end

  def query
    @inbound.query_channel_inbound!
    redirect_to delivery_inbounds_path
  end

  private

  def find_inbound
    @inbound = Inbound.find_by id: params[:id]
  end

  def find_live_show
    @live_show = LiveShow.find_by id: params[:live_show_id]
  end
end

app/controllers/delivery/index_controller.rb
class Delivery::IndexController < Delivery::ApplicationController
  # before_action :admin_required  

  def dashboard
    redirect_to delivery_live_shows_path
  end
end

app/controllers/delivery/live_shows_controller.rb
class Delivery::LiveShowsController < Delivery::ApplicationController  

	before_action :find_live_show, except: [:index, :new, :create, :upload_preview, :preview_page, :fresh_page]
  before_action :admin_required, except: [:preview_page, :fresh_page] 


  def index
    @live_shows = LiveShow.order('created_at DESC')
  end

  def show    
    @products = @live_show.products.order('created_at DESC')
  end

  def new
    @live_show = LiveShow.new
  end

  def create    
  	@live_show = @current_admin.live_shows.build live_show_params
  	if @live_show.save
  	  redirect_to delivery_live_show_path(@live_show)
    else
      render :new
    end
  end

  def edit
  end

  def update        
    if @live_show.update_attributes(live_show_params)
      redirect_to delivery_live_shows_path
    else
      render :edit
    end
  end

  def open
  	@live_show.update_attribute(:status, 'onair')
  	redirect_to delivery_live_show_path(@live_show)
  end

  def close
  	@live_show.update_attributes!({status: 'closed', countdown: params[:countdown], close_time: Time.now})
    @live_show.jpush_notify_room_closed
  	redirect_to delivery_live_shows_path
  end

  # 默认人民币
  def clearing_price
    clearing_price = (params[:product_price].to_f * @live_show.exchange_rate.to_f).ceil
    render json: { clearing_price: clearing_price }
  end

  def shopping_list
    @order_items = @live_show.order_items
                             .select("*, sum(quantity) as quantity")
                             .joins(:order)
                             .includes(:sku, :product)
                             .where('orders.status = ?', Order.statuses[:paid])
                             .group("order_items.sku_id")
    
  end

  #===========================>
  #直播室预展页面
  def preview_page
    @products = LiveShow.where(subject: 'Costco Beta test Show 12/2014').first.products    
    render layout: false
  end

  def fresh_page
    @products = LiveShow.where(subject: 'Sephora 丝芙兰 Fresh专场').first.products    
    render layout: false    
  end

  #============================>

  private

  def live_show_params
    params.require(:live_show).permit(
      :subject, :description, :preview, 
      :start_time, :close_time,
      :html_url,
      :countdown, 
      :exchange_rate,
      :location
    )
  end

  def find_live_show  
  	@live_show = LiveShow.find params[:id]
  end

end

app/controllers/delivery/materials_controller.rb
class Delivery::MaterialsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show

  def create
    material = @live_show.materials.build
    material.user_id = @current_admin.id
    material.material_type = params[:material].content_type.split('/').last.downcase
    material.resource = params[:material]
    state = material.save
    render json: { success: state, material: material }    
  end

  private

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end
end

app/controllers/delivery/messages_controller.rb
class Delivery::MessagesController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show

  def index
    @messages = @live_show.messages.includes(:user).order("messages.created_at ASC")
    @messages = @messages.paginate(per_page: 20, page: params[:page])
  end 

  private

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end  
end

app/controllers/delivery/orders_controller.rb
class Delivery::OrdersController < Delivery::ApplicationController
  before_action :admin_required
  before_action :find_order, except: [:index]

  def index
    @live_show = LiveShow.find_by id: params[:live_show_id]     
    @live_show = LiveShow.where('status <> ?', 'pending').first if !@live_show.present?   
    inbounds = @live_show.inbounds
    @inbound_finish = inbounds.present? ? ( inbounds.first.status == 'finish' ) : false
    @orders = @live_show.orders.order('user_id DESC, created_at DESC').includes(:user, :order_items, :recipient)    
  end

  def check_prepare_products        
    live_show = @order.live_show
    live_show.inbounds.each do |ib|      
      ib.uszcn_query_inbound! #if Time.now - ib.updated_at > 30.minutes                            
    end

    inbounded_lists = live_show.merge_inbounds
    @order.order_items.each do |oi|
      #TODO 去掉已经出库的数量
      a = inbounded_lists[oi.sku_id.to_i].blank? ? 0 : inbounded_lists[oi.sku_id.to_i][:inbounded_quantity]
      render text: {abundant: false}.to_json and return if a < oi.quantity
    end
    shipmentfee = @order.carriage.to_i
    @order.update_attribute(:status, 'freight')
    @order.shipmentfee = shipmentfee
    @order.save!
    render text: {abundant: true}.to_json
  end

  def notify_carriage
    begin      
      @order.notify_carriage
      render text: {success: true}.to_json
    rescue => e      
      render text: {success: false}.to_json
    end
  end

  def notify_tax    
    outbound = Outbound.find_by order_id: @order.id
    outbound.notify_tax
    render text: {success: true}.to_json
  end  


  def find_order
    @order = Order.find_by id: params[:id]
  end

end

app/controllers/delivery/outbounds_controller.rb
class Delivery::OutboundsController < Delivery::ApplicationController
  before_action :admin_required
  
  def create 
    ActiveRecord::Base.transaction do
      begin
        order = Order.find_by id: params[:order_id]
        ib = Inbound.find_by live_show_id: order.live_show_id
        ob = Outbound.new
        ob.inbound_id = ib.id
        ob.order_id = order.id
        ob.outbound_no = ''
        ob.save!        
        raise '出库出错!' if ob.notify_uszcn!.blank?
        
        success = true
      rescue => e        
        success = false
        raise ActiveRecord::Rollback        
      end
      render text: {success: true}.to_json
    end
    
  end

  def query
    outbound = Outbound.find_by id: params[:id]    
    ret = outbound.query_shopshow_outbound    

    Rails.logger.info ret.inspect
    Rails.logger.info "***********************"        
    if ret["success"]
      order = Order.find_by id: outbound.order_id
      ActiveRecord::Base.transaction do 
        if !ret["data"]["outbound_code"].blank?
          order.update_attributes! status: 'outbound'
        end
        outbound.update_attributes! outbound_no: ret["data"]["outbound_code"]
        render html: Outbound.format_outbound_state(ret["data"]["item_list"])
      end
    else
      render html: "订单出库异常！请联系技术人员!"
    end  

          
  end

end

app/controllers/delivery/sessions_controller.rb
class Delivery::SessionsController < Delivery::ApplicationController
  layout false
  before_action :no_login_required, only: [:new, :create]

  def new
  end

  def create
    @admin = User.auth(params[:login], params[:password])

    if @admin && @admin.admin?
      login_as @admin
      redirect_to delivery_root_path
    else
      flash[:warning] = "帐号或者密码错误"
      redirect_to delivery_login_path
    end    
  end

  def destroy
    logout
    flash[:warning] = "您已登出管理后台"
    redirect_to delivery_login_path
  end  
end

app/helpers/delivery/application_helper.rb
module Delivery
  module ApplicationHelper
    def format_message(message)
      case message.celltype
      when "UserText", "AdminText"
        content_tag "div", class: 'text-muted' do
          message.content
        end
      when "AdminImage"
        img = image_tag message.image_url
        "<p class='mt-10'>#{img}</p>".html_safe
      when "Product"
        %Q(
          <div class="panel panel-default">
            <div class="panel-heading">
              <a href="#{edit_delivery_product_path(message.product, live_show_id: message.live_show_id)}">#{message.product.name_en}</a>
            </div>
            <div class="panel-body">
              <img src="#{message.product.cover.resource_url}">
            </div>
          </div>
        ).html_safe
      end
    end
  end
end

app/helpers/delivery/inbounds_helper.rb
module Delivery
  module InboundsHelper
    def flag_tag(inbound)
      klass = "label label-"
      case inbound.status
      when "pending"
        klass << "default"
      when "finish"
        klass << "success"
      else
        klass << "danger"
      end

      content_tag 'span', class: klass do
        inbound.status.upcase
      end
    end
  end
end

app/helpers/delivery/orders_helper.rb
module Delivery
  module OrdersHelper
    def order_flag_tag order
      klass = "btn btn-xs btn-"
      case order.status
      when "paid"
        klass << "success"
      when "failed"
        klass << "danger"
      else
        klass << "default"
      end

      content_tag 'a', class: klass do
        order.status.upcase
      end      
    end
  end
end

app/helpers/delivery/products_helper.rb
module Delivery
  module ProductsHelper
    def status_tag product
      klass = "label"

      case product.status
      when "draft", "locked"
        klass << " label-default"
      when "previewing"
        klass << " label-info"
      when "published"
        klass << " label-success"
      end
          
      %Q(<span class="#{klass}">#{product.readable_status}</span>).html_safe
    end
  end
end

app/views/delivery/live_shows/_detail.html.slim
.detail.clearfix
  .pull-left.cover
    img src="#{@live_show.preview_url}" width="300" height="180"
  .pull-left.info
    h4= @live_show.subject
    p.text-muted= @live_show.description || "没有添加专场介绍"
    p.start
      span 开始时间：#{@live_show.start_time.strftime('%Y-%m-%d')}
      span.text-warning= @live_show.start_time.strftime('%H:%M:%S')
    .location.text-muted.mt-50= @live_show.location || "没有添加地点"
  .pull-right
    .clearfix
      .btn-group
        a.btn.btn-blue.active.icon href=edit_delivery_live_show_path(@live_show)
          i.ss.ss-edit
        a.btn.btn-blue href=edit_delivery_live_show_path(@live_show) 编辑信息
    - if @live_show.status == 'pending' || @live_show.status=='previewing'
      .clearfix.mt-10
        .btn-group
          a.btn.btn-green.active.icon href=open_delivery_live_show_path(@live_show) onclick="{if(confirm('确定开启直播室?')){return true;}return false;}"
            i.ss.ss-play
          a.btn.btn-green href=open_delivery_live_show_path(@live_show) onclick="{if(confirm('确定开启直播室?')){return true;}return false;}" 开始直播
    - if @live_show.status == 'onair'
      .clearfix.mt-10
        .btn-group
          a.btn.btn-red.active.icon onclick="App.LiveShow.closeLiveShow('#{@live_show.id}', '#{@live_show.countdown}')"
            i.ss.ss-power-off
          a.btn.btn-red onclick="App.LiveShow.closeLiveShow('#{@live_show.id}', '#{@live_show.countdown}')" 结束直播

app/views/delivery/live_shows/_form.html.slim
= javascript_include_tag 'delivery/live_show'

.page-header
  h3.clearfix 创建直播专场
  .text-muted * 号为必填项
  hr
.page-content
  = simple_form_for @live_show, url: form_url, html: { class: 'form-horizontal' } do |f|
    .form-group
      .col-sm-2
      .col-sm-6.preview.clearfix
        - if @live_show.preview.blank?
          .plus
            = f.file_field :preview, as: :file
        - else
          .image-preview
            img width="300" height="180" src="#{@live_show.preview_url}"
            .ops
              button.btn.btn-default type="button"
                i.fa.fa-trash.mr-5
                span 删除
          .plus style="display:none;"
            = f.file_field :preview, as: :file
    = f.input :subject, wrapper: :horizontal_form
    hr
    = f.input :location, wrapper: :horizontal_form
    hr
    = f.input :description, wrapper: :horizontal_form, as: :text do
      = f.input_field :description, class: 'form-control'
      .text-muted.mt-5: small 例如 “低价 Levis's 牛仔裤，超值丝芙兰全品类”
    hr
    = f.input :start_time, wrapper: :horizontal_form_xs, as: :string, id: "start_time"
    hr
    = f.input :countdown, wrapper: :horizontal_form_xs, as: :string  
      = f.input_field :countdown, class: 'form-control'
      .text-muted.mt-5: small 以分钟为单位 例如(15)          
    hr
    = f.input :html_url, wrapper: :horizontal_form_xs
    hr
    = f.input :exchange_rate, wrapper: :horizontal_form_xs do
      = f.input_field :exchange_rate, class: 'form-control'
      .mt-5
        small: a href='#' 实时外汇牌价     
    hr
    .form-group
      label.control-label.col-sm-2
      .col-sm-2
        button.btn.btn-success.btn-block.btn-lg type='submit'
          i.fa.fa-check
          span.ml-5 保存

app/views/delivery/live_shows/_nav.html.slim
ul.nav.nav-tabs
  li class=('active' if params[:action] == 'show')
    a href="#{delivery_live_show_path(@live_show)}"
      span 产品管理
      span.badge.ml-5= @live_show.products.count
  li class=('active' if params[:action] == 'index')
    a href="#{delivery_live_show_messages_path(@live_show)}"
      span 直播实录
  li class=('active' if params[:action] == 'shopping_list')
    a href="#{shopping_list_delivery_live_show_path(@live_show)}"
      span 采购清单

app/views/delivery/live_shows/edit.html.slim
= render partial: "delivery/live_shows/form", locals: { form_url: delivery_live_show_path(@live_show) }

app/views/delivery/live_shows/fresh_page.html.slim
doctype html
html xmlns="http://www.w3.org/1999/xhtml" 
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Untitled Document
    link href="style.css" rel="stylesheet" type="text/css"
  body
    css:
      body{margin: 0px;padding: 0px;}
      .banner img{width: 100%;}
      .product_box{width: 46%;float: left;margin: 10px 2% 10px 2%;}
      .product_box img{width:100%;}
      .product_name_box {background-color: #f1f1f1;border-bottom: solid 1px #cccccc;height: 110px;}
      .product_name_box h1{margin: 0px;padding: 10px;font-size: 14px;color: #454545;}
      .product_name_box p{margin: 0px;padding: 0px 10px 10px 10px;font-size: 16px;color: #ff4e00;}
        
    .banner
      = image_tag "fresh/head.png"    
    - @products.each do |p|
      .product_box
        = image_tag p.cover.resource_url, size: '150x150'
        .product_name_box
          h1= p.name_en.truncate(55)
          p 
            | $
            = p.price

app/views/delivery/live_shows/index.html.slim
.page-header
  h1.clearfix
    | 我的直播场次
    .pull-right
      .btn-group
        a.btn.btn-green.active.icon: i.fa.fa-plus
        a.btn.btn-green href=new_delivery_live_show_path 创建直播专场     
.page-content
  table.table
    thead
      tr
        th #
        th 主题
        th 开始时间
        / th 结束时间
        th 预展URL
        th 汇率
        th 创建时间                
        th 状态
        th 操作
    tbody
      - @live_shows.each_with_index do |lv, i|
        tr
          td= i + 1
          td
            a href="#{delivery_live_show_path(lv)}"= lv.subject
          td= lv.start_time.strftime('%F %T')          
          td= lv.html_url
          td= lv.exchange_rate
          td= lv.created_at.strftime('%F %T')          
          td
            - klass = (lv.status == 'onair' ? 'btn-success' : 'btn-danger')
            a.btn.btn-xs class="#{klass}"
              = lv.readable_status
          td
            a href=edit_delivery_live_show_path(lv) 编辑 

app/views/delivery/live_shows/new.html.slim
= render partial: "delivery/live_shows/form", locals: { form_url: delivery_live_shows_path(@live_show) }

app/views/delivery/live_shows/preview_page.html.slim
doctype html
html xmlns="http://www.w3.org/1999/xhtml" 
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Untitled Document
    link href="style.css" rel="stylesheet" type="text/css"
  body
  	css:
      body{margin: 0px;padding: 0px;}
      .banner img{width: 100%;}
      .product_box{width: 46%;float: left;margin: 10px 2% 10px 2%;}
      .product_box img{width:100%;}
      .product_name_box {background-color: #f1f1f1;border-bottom: solid 1px #cccccc;height: 110px;}
      .product_name_box h1{margin: 0px;padding: 10px;font-size: 14px;color: #454545;}
      .product_name_box p{margin: 0px;padding: 0px 10px 10px 10px;font-size: 16px;color: #ff4e00;}
			 	
    .banner
      = image_tag "costco/banner.jpg"    
    - @products.each do |p|
	    .product_box
	      = image_tag p.cover.resource_url, size: '150x150'
	      .product_name_box
	        h1= p.name_en.truncate(55)
	        p 
	        	| $
	        	= p.price

app/views/delivery/live_shows/shopping_list.html.slim
= javascript_include_tag 'delivery/live_show'
.page-content
  = render "delivery/live_shows/detail"
  .list-container
    = render "delivery/live_shows/nav"
    .list-content
      .list-options.clearfix
        .pull-left
          .btn-group
            a.btn.btn-small.btn-blue.active.icon: i.fa.fa-refresh
            a.btn.btn-small.btn-blue 刷新
        .pull-right
          .btn-group
            a.btn.btn-small.btn-red.active.icon: i.fa.fa-plus
            a.btn.btn-small.btn-red href="#{new_delivery_live_show_product_path(@live_show)}" 生成入库单
            
      table.table.table-striped.table-hover
        thead
          tr
            th #
            th SKU
            th 商品图
            th 商品名称
            th 商品描述
            th 商品规格
            th 重量(KG)
            th 件数
            th 单价(美元)
            th 总价(美元)
        tbody
          - @order_items.each_with_index do |item, i|
            tr
              td= i + 1
              td= item.sku.sku_id.upcase
              td
                = image_tag item.product.cover.resource_url, size: '40x40'
              td= item.product.name_en
              td= item.product.description
              td= item.sku.prop_to_text
              td= item.sku.weight
              td= item.quantity
              td= item.product.price
              td= item.calc_in_total

        tr.warning
          td 总计
          td colspan="6"
          td= @order_items.map(&:quantity).sum
          td
          td= @order_items.map{ |is| is.calc_in_total }.sum

app/views/delivery/live_shows/show.html.slim
= javascript_include_tag 'delivery/live_show'
.page-content
  = render "delivery/live_shows/detail"
  .list-container
    = render "delivery/live_shows/nav"
    .list-content
      .list-options.clearfix
        .pull-left
          .btn-group
            a.btn.btn-small.btn-red.active.icon: i.fa.fa-plus
            a.btn.btn-small.btn-red href="#{new_delivery_live_show_product_path(@live_show)}" 添加产品
          .btn-group.ml-15
            a.btn.btn-small.btn-blue.active.icon: i.fa.fa-refresh
            a.btn.btn-small.btn-blue href="#{url_for}" 刷新         
        .pull-right
          select.form-control
            = options_for_select Product.statuses_i18n.invert, params[:status]
      = render "share/flash_messages"
      table.table
        thead
          tr
            th 产品图
            th 名称
            th 介绍
            th 价格
            th 状态
            th 操作
        tbody
          - @products.each do |product|
            tr
              td
                - if product.cover
                  = image_tag product.cover.resource_url, size: '50x50'
              td= product.name_en
              td= product.description
              td.price
                i.fa.fa-dollar
                span= product.price
              td= status_tag(product)
              td
                a href="#{edit_delivery_product_path(product, live_show_id: product.live_show_id)}" 编辑