config/routes.rb
Rails.application.routes.draw do
  require 'api'
  mount Shopshow::API => "/"
  require 'uszcn_api'
  mount Shopshow::Uszcn => '/'

  root to: 'welcome#index'
  post 'update_avatar', to: 'welcome#update_avatar'
  post 'update_recipient', to: 'welcome#update_recipient'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 手机客户端
  namespace :mobile do
    resources :users, only: [:new, :create, :show] do
      collection do
        post :send_code
        post :verify_code
        post :check_name
        get :regist_succeed
      end
    end

    scope :shopping_cart do
      get :goods, to: 'shopping_cart#goods'
      post :update_item, to: 'shopping_cart#update_item'
      post :remove, to: 'shopping_cart#remove'
      post :remove_selected, to: 'shopping_cart#remove_selected'
      get :confirm, to: 'shopping_cart#confirm'
    end
    get :orders, to: 'orders#index'
    post :orders, to: 'orders#index'
    
    resources :orders do 
      post :outbound_msg
    end
    

  end  
  post '/mobile/orders/handle_alipay_notify' => 'mobile/orders#handle_alipay_notify'
  
  scope :jabber do
    post :prebind, to: 'jabber#prebind'
  end

  # 买手后台系统
  namespace :delivery do
    root to: 'index#dashboard'

    get 'login', to: 'sessions#new', as: 'login'    
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :materials, only: [:create]

    resources :inbounds do
      member do
        get :query
      end
    end

    resources :orders do
      member do
        post :outbound       
        post :check_prepare_products 
        post :notify_carriage
        post :notify_tax        
      end
    end

    resources :outbounds do 
      member do
        get :query                        
      end                
    end

    resources :live_shows do
      member do        
        get :open
        get :close
        post :clearing_price
        get :shopping_list        
      end

      resources :products, shallow: true
      resources :messages, shallow: true
    end
  end

  get 'costco' => 'delivery/live_shows#preview_page'  
  get 'fresh' => 'delivery/live_shows#fresh_page'
    
  # 运维后台
  namespace :cpanel do
    root to: 'live_shows#index'

    scope :faqs do
      get '1' => 'faqs#faq1'      
      get '2' => 'faqs#faq2'      
      get '3' => 'faqs#faq3'      
    end

    scope :trailer do
      get 'costco' => 'trailers#costco'      
      get 'next' => 'trailers#next'
    end

    resources :live_shows do
      member do
        get :products
        post :products
        get :close        
      end
      get :choose_material
    end

    resources :users

    resources :products do
      member do
        post :publish
      end
    end

    resources :materials, only: [:create]

    resources :orders do
      resources :items, only: [:index]
    end
  end
end

app/controllers/delivery/application_controller.rb
class Delivery::ApplicationController < ActionController::Base
  layout 'delivery'
  helper_method :admin_login?, :current_admin

  private

  class AdminAccessDenied < Exception; end

  def admin_required
    unless admin_login?
      flash[:warning] = "请先登录"
      redirect_to delivery_login_path
    end    
  end

  def admin_login?
    !!current_admin
  end

  def current_admin
    @current_admin ||= login_from_session unless defined?(@current_admin)
    @current_admin
  end

  def login_as(admin)
    session[:admin_id] = admin.id
    @current_admin = admin
  end

  def logout
    session.delete :admin_id
    @current_admin = nil
  end

  def login_from_session
    return nil if session[:admin_id].blank?
    begin
      User.find(session[:admin_id]) 
    rescue
      session[:admin_id] = nil
    end 
  end

  def no_login_required
    if admin_login?
      redirect_to delivery_root_url
    end
  end  
end

app/controllers/delivery/inbounds_controller.rb
class Delivery::InboundsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show, only: [:new]
  before_action :find_inbound, only: [:show, :query]

  def index
    @inbounds = Inbound.order('created_at DESC')
  end

  def show
    @inbound_skus = @inbound.inbound_skus.includes(:sku, :inbound).order('created_at DESC')
  end

  def new
    @live_shows = LiveShow.all
    if @live_show.present?
      @products = @live_show.products.order('created_at DESC')
      @orders = @live_show.orders.order('created_at DESC, user_id DESC').includes(:user, :order_items)  
      @order_items = @live_show.order_items
                               .select("*, sum(quantity) as quantity")
                               .joins(:order)
                               .includes(:sku, :product)
                               .where('orders.status = ?', Order.statuses[:paid])
                               .group("order_items.sku_id")
    end
  end

  def create
    ActiveRecord::Base.transaction do
      channel = Channel.default
      inbound = channel.inbounds.build
      inbound.status = 0
      inbound.live_show_id = params[:live_show_id]
      inbound.save!

      skus = params[:skus]
      skus.each do |k, v|
        i_s = inbound.inbound_skus.build      
        i_s.sku_id = v[:sku_id]
        i_s.quantity = v[:amount].to_i
        i_s.save!
      end

      inbounded = skus.values.sum { |h| h[:amount].to_i }
      inbound.update_attributes!(:quantity => inbounded)
      inbound.notify_channel_inbound
    end

    render json: { success: true }
  end

  def query
    @inbound.query_channel_inbound!
    redirect_to delivery_inbounds_path
  end

  private

  def find_inbound
    @inbound = Inbound.find_by id: params[:id]
  end

  def find_live_show
    @live_show = LiveShow.find_by id: params[:live_show_id]
  end
end

app/controllers/delivery/index_controller.rb
class Delivery::IndexController < Delivery::ApplicationController
  # before_action :admin_required  

  def dashboard
    redirect_to delivery_live_shows_path
  end
end

app/controllers/delivery/live_shows_controller.rb
class Delivery::LiveShowsController < Delivery::ApplicationController  

	before_action :find_live_show, except: [:index, :new, :create, :upload_preview, :preview_page, :fresh_page]
  before_action :admin_required, except: [:preview_page, :fresh_page] 


  def index
    @live_shows = LiveShow.order('created_at DESC')
  end

  def show    
    @products = @live_show.products.order('created_at DESC')
  end

  def new
    @live_show = LiveShow.new
  end

  def create    
  	@live_show = @current_admin.live_shows.build live_show_params
  	if @live_show.save
  	  redirect_to delivery_live_show_path(@live_show)
    else
      render :new
    end
  end

  def edit
  end

  def update        
    if @live_show.update_attributes(live_show_params)
      redirect_to delivery_live_shows_path
    else
      render :edit
    end
  end

  def open
  	@live_show.update_attribute(:status, 'onair')
  	redirect_to delivery_live_show_path(@live_show)
  end

  def close
  	@live_show.update_attributes!({status: 'closed', countdown: params[:countdown], close_time: Time.now})
    @live_show.jpush_notify_room_closed
  	redirect_to delivery_live_shows_path
  end

  # 默认人民币
  def clearing_price
    clearing_price = (params[:product_price].to_f * @live_show.exchange_rate.to_f).ceil
    render json: { clearing_price: clearing_price }
  end

  def shopping_list
    @order_items = @live_show.order_items
                             .select("*, sum(quantity) as quantity")
                             .joins(:order)
                             .includes(:sku, :product)
                             .where('orders.status = ?', Order.statuses[:paid])
                             .group("order_items.sku_id")
    
  end

  #===========================>
  #直播室预展页面
  def preview_page
    @products = LiveShow.where(subject: 'Costco Beta test Show 12/2014').first.products    
    render layout: false
  end

  def fresh_page
    @products = LiveShow.where(subject: 'Sephora 丝芙兰 Fresh专场').first.products    
    render layout: false    
  end

  #============================>

  private

  def live_show_params
    params.require(:live_show).permit(
      :subject, :description, :preview, 
      :start_time, :close_time,
      :html_url,
      :countdown, 
      :exchange_rate,
      :location
    )
  end

  def find_live_show  
  	@live_show = LiveShow.find params[:id]
  end

end

app/controllers/delivery/materials_controller.rb
class Delivery::MaterialsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show

  def create
    material = @live_show.materials.build
    material.user_id = @current_admin.id
    material.material_type = params[:material].content_type.split('/').last.downcase
    material.resource = params[:material]
    state = material.save
    render json: { success: state, material: material }    
  end

  private

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end
end

app/controllers/delivery/messages_controller.rb
class Delivery::MessagesController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show

  def index
    @messages = @live_show.messages.includes(:user).order("messages.created_at ASC")
    @messages = @messages.paginate(per_page: 20, page: params[:page])
  end 

  private

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end  
end

app/controllers/delivery/orders_controller.rb
class Delivery::OrdersController < Delivery::ApplicationController
  before_action :admin_required
  before_action :find_order, except: [:index]

  def index
    @live_show = LiveShow.find_by id: params[:live_show_id]     
    @live_show = LiveShow.where('status <> ?', 'pending').first if !@live_show.present?   
    inbounds = @live_show.inbounds
    @inbound_finish = inbounds.present? ? ( inbounds.first.status == 'finish' ) : false
    @orders = @live_show.orders.order('user_id DESC, created_at DESC').includes(:user, :order_items, :recipient)    
  end

  def check_prepare_products        
    live_show = @order.live_show
    live_show.inbounds.each do |ib|      
      ib.uszcn_query_inbound! #if Time.now - ib.updated_at > 30.minutes                            
    end

    inbounded_lists = live_show.merge_inbounds
    @order.order_items.each do |oi|
      #TODO 去掉已经出库的数量
      a = inbounded_lists[oi.sku_id.to_i].blank? ? 0 : inbounded_lists[oi.sku_id.to_i][:inbounded_quantity]
      render text: {abundant: false}.to_json and return if a < oi.quantity
    end
    shipmentfee = @order.carriage.to_i
    @order.update_attribute(:status, 'freight')
    @order.shipmentfee = shipmentfee
    @order.save!
    render text: {abundant: true}.to_json
  end

  def notify_carriage
    begin      
      @order.notify_carriage
      render text: {success: true}.to_json
    rescue => e      
      render text: {success: false}.to_json
    end
  end

  def notify_tax    
    outbound = Outbound.find_by order_id: @order.id
    outbound.notify_tax
    render text: {success: true}.to_json
  end  


  def find_order
    @order = Order.find_by id: params[:id]
  end

end

app/controllers/delivery/outbounds_controller.rb
class Delivery::OutboundsController < Delivery::ApplicationController
  before_action :admin_required
  
  def create 
    ActiveRecord::Base.transaction do
      begin
        order = Order.find_by id: params[:order_id]
        ib = Inbound.find_by live_show_id: order.live_show_id
        ob = Outbound.new
        ob.inbound_id = ib.id
        ob.order_id = order.id
        ob.outbound_no = ''
        ob.save!        
        raise '出库出错!' if ob.notify_uszcn!.blank?
        
        success = true
      rescue => e        
        success = false
        raise ActiveRecord::Rollback        
      end
      render text: {success: true}.to_json
    end
    
  end

  def query
    outbound = Outbound.find_by id: params[:id]    
    ret = outbound.query_shopshow_outbound    

    Rails.logger.info ret.inspect
    Rails.logger.info "***********************"        
    if ret["success"]
      order = Order.find_by id: outbound.order_id
      ActiveRecord::Base.transaction do 
        if !ret["data"]["outbound_code"].blank?
          order.update_attributes! status: 'outbound'
        end
        outbound.update_attributes! outbound_no: ret["data"]["outbound_code"]
        render html: Outbound.format_outbound_state(ret["data"]["item_list"])
      end
    else
      render html: "订单出库异常！请联系技术人员!"
    end  

          
  end

end

app/controllers/delivery/products_controller.rb
class Delivery::ProductsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show, only: [:new, :create, :edit, :update]

  def index
  end

  def new
    @product = @live_show.products.build
    find_materials
    (2 -  @product.specifications.size).times do
      @product.specifications.build
    end    
  end

  def create
    ActiveRecord::Base.transaction do
      @product = @live_show.products.build product_params
      @product.author_id = @current_admin.id
      set_materials
      set_cover

      if @product.save
        publish_product!
        redirect_to delivery_live_show_path(@live_show)
      else
        (2 -  @product.specifications.size).times do
          @product.specifications.build
        end
        render :new
      end
    end
  end

  def edit
    @product = Product.find params[:id]
    find_materials
    (2 -  @product.specifications.size).times do
      @product.specifications.build
    end     
  end

  def update
    Product.transaction do
      @product = Product.find params[:id]

      if @product.update_attributes(product_params)
        set_materials
        set_cover
        publish_product!
        redirect_to delivery_live_show_path(@live_show)
      else
        (2 -  @product.specifications.size).times do
          @product.specifications.build
        end        
        render :edit 
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :id, :cover_id,
      :name_en, :description, :price, :weight,
      :weight_unit, :live_show_id,
      :picture_ids, :status, specifications_attributes: [:id, :name, :value]
    )
  end

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end

  def find_materials
    @materials = Material.where(id: @product.picture_ids.split(",")).order('created_at desc')
  end

  def set_materials
    find_materials
    @product.materials = @materials
  end

  def set_cover
    if @product.cover_id.blank?
      @product.cover_id = @materials.first.try(:id)
    end    
  end

  def publish_product!
    if @product.published_at.blank? and @product.published?
      @product.publish! 
    end    
  end
end

app/controllers/delivery/sessions_controller.rb
class Delivery::SessionsController < Delivery::ApplicationController
  layout false
  before_action :no_login_required, only: [:new, :create]

  def new
  end

  def create
    @admin = User.auth(params[:login], params[:password])

    if @admin && @admin.admin?
      login_as @admin
      redirect_to delivery_root_path
    else
      flash[:warning] = "帐号或者密码错误"
      redirect_to delivery_login_path
    end    
  end

  def destroy
    logout
    flash[:warning] = "您已登出管理后台"
    redirect_to delivery_login_path
  end  
end

app/helpers/delivery/application_helper.rb
module Delivery
  module ApplicationHelper
    def format_message(message)
      case message.celltype
      when "UserText", "AdminText"
        content_tag "div", class: 'text-muted' do
          message.content
        end
      when "AdminImage"
        img = image_tag message.image_url
        "<p class='mt-10'>#{img}</p>".html_safe
      when "Product"
        %Q(
          <div class="panel panel-default">
            <div class="panel-heading">
              <a href="#{edit_delivery_product_path(message.product, live_show_id: message.live_show_id)}">#{message.product.name_en}</a>
            </div>
            <div class="panel-body">
              <img src="#{message.product.cover.resource_url}">
            </div>
          </div>
        ).html_safe
      end
    end
  end
end

app/helpers/delivery/inbounds_helper.rb
module Delivery
  module InboundsHelper
    def flag_tag(inbound)
      klass = "label label-"
      case inbound.status
      when "pending"
        klass << "default"
      when "finish"
        klass << "success"
      else
        klass << "danger"
      end

      content_tag 'span', class: klass do
        inbound.status.upcase
      end
    end
  end
end

app/helpers/delivery/orders_helper.rb
module Delivery
  module OrdersHelper
    def order_flag_tag order
      klass = "btn btn-xs btn-"
      case order.status
      when "paid"
        klass << "success"
      when "failed"
        klass << "danger"
      else
        klass << "default"
      end

      content_tag 'a', class: klass do
        order.status.upcase
      end      
    end
  end
end

app/helpers/delivery/products_helper.rb
module Delivery
  module ProductsHelper
    def status_tag product
      klass = "label"

      case product.status
      when "draft", "locked"
        klass << " label-default"
      when "previewing"
        klass << " label-info"
      when "published"
        klass << " label-success"
      end
          
      %Q(<span class="#{klass}">#{product.readable_status}</span>).html_safe
    end
  end
end

app/views/delivery/inbounds/index.html.slim
.page-header
  h1.clearfix
    | 入库单列表
    .pull-right
      a.btn.btn-primary href="#{new_delivery_inbound_path}"
        i.fa.fa-plus
        span.ml-5 新建入库单
.page-content
  table.table.table-hover
    thead
      tr
        th #
        th 入库单号
        th 渠道
        th SKU 总数
        th 入库数量
        th 创建时间
        th 更新时间
        th 状态
        th -
    tbody
      - @inbounds.each_with_index do |inbound, i|
        tr
          td= i + 1
          td
            a href="#{delivery_inbound_path(inbound)}"= inbound.channel_inbound_no
          td= inbound.channel.name
          td= inbound.quantity
          td= inbound.inbounded_quantity
          td= inbound.created_at.strftime('%F %T')
          td= inbound.updated_at.strftime('%F %T')
          td= inbound.readable_status
          td 
            a.queryInbound href="#this" path="#{query_delivery_inbound_path(inbound.id)}": i.fa.fa-refresh          
javascript:
  $(function(){

    $('a.queryInbound').click(function(){
      $(this).button('loading');
      var path = $(this).attr('path')
      window.location.href = path;
    })
  
  })

app/views/delivery/inbounds/new.html.slim
.page-header
  h1.clearfix
    | New Inbound
    .pull-right
      = form_tag new_delivery_inbound_path(live_show_id: params[:live_show_id]), method: :get do
        = select_tag :live_show_id, options_from_collection_for_select(LiveShow.all, "id", "subject", @live_show.try(:id)), class: 'form-control', prompt: '--请选择直播场次--'
.page-content
  - if @live_show.blank?
    p.text-center.text-muted 请选择直播场次
  - else
    table.table.table-striped.table-hover
      thead
        tr
          th #
          th SKU
          th 商品图
          th 商品名称
          th 商品描述
          th 商品规格
          th 重量(KG)
          th 件数
          th 单价(美元)
          th 总价(美元)
      tbody
        - @order_items.each_with_index do |item, i|
          tr.sku-list sku-id="#{item.sku.try(:id)}" sku-amount=item.quantity
            td= i + 1
            td= item.sku.sku_id.upcase
            td
              = image_tag item.product.cover.resource_url, size: '40x40'
            td= item.product.name_en
            td= item.product.description
            td= item.sku.prop_to_text
            td= item.sku.weight
            td= item.quantity
            td= item.product.price
            td= item.calc_in_total

      tr.warning
        td 总计
        td colspan="6"
        td= @order_items.map(&:quantity).sum
        td
        td= @order_items.map{ |is| is.calc_in_total }.sum  

    .footer.clearfix
      - if @live_show.inbounds.blank?
        a#inboundAll.btn.btn-danger.btn-lg.pull-right href="#" 
          i.fa.fa-warning 
          span.ml-10 生成入库清单
      - else        
        .pull-right
          i.fa.fa-check
            span.ml-10 已经全部预报入库

javascript:
  $(function () {
    $('form select').change(function () {
      $(this).parent().submit();
    });


    $('a#inboundAll').click(function(){
      var skus = [];

      $('tr.sku-list').each(function(){
        var $this = $(this);
        skus.push({
          sku_id : $this.attr('sku-id'),
          amount : $this.attr('sku-amount')
        })
      });
      
      $(this).button('loading');
      $.post('/delivery/inbounds', { skus: skus, live_show_id: "#{@live_show.try(:id)}" }, function(res){      
        window.location.reload();
      })
    });
      

  });

app/views/delivery/inbounds/show.html.slim
.page-header
  h1.clearfix
    | Inbound's Skus <small>Inbound No. #{@inbound.channel_inbound_no}</small>
    .pull-right
      a.btn.btn-primary.queryInbound href="#this" data-inbound_id="#{@inbound.id}"
        i.fa.fa-refresh
        span.ml-5 刷新入库状态

.page-content
  table.table.table-striped.table-hover
    thead
      tr
        th #
        th SKU
        th 商品图
        th 商品名称
        th 商品描述
        th 重量(KG)
        th 件数
        th 单价(美元)
        th 总价(美元)
        th 入库件数
    tbody
      - @inbound_skus.each_with_index do |is, i|
        tr
          td= i + 1
          td= is.sku.sku_id.upcase
          td
            = image_tag is.product.cover.resource_url, size: '40x40'
          td= is.product.name_en
          td= is.product.description
          td= is.sku.weight
          td= is.quantity
          td= is.product.price
          td= is.calc_in_total
          td= is.inbounded_quantity
      tr.warning
        td Total
        td colspan="5"
        td= @inbound.quantity
        td
        td= @inbound_skus.map{ |is| is.calc_in_total }.sum
        td= @inbound_skus.sum(:inbounded_quantity)

javascript:
  $(function () {
    $('a.queryInbound').click(function () {
      var $this = $(this);
      var inbound_id = $this.data("inbound_id");
      var url = "#{query_delivery_inbound_path(@inbound)}";

      $.post(url, function (res) {
        if (res.success) {
          window.location.reload();
        }
      }, 'json');
    });
  });