config/routes.rb
Rails.application.routes.draw do
  require 'api'
  mount Shopshow::API => "/"
  require 'uszcn_api'
  mount Shopshow::Uszcn => '/'

  root to: 'welcome#index'
  post 'update_avatar', to: 'welcome#update_avatar'
  post 'update_recipient', to: 'welcome#update_recipient'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 手机客户端
  namespace :mobile do
    resources :users, only: [:new, :create, :show] do
      collection do
        post :send_code
        post :verify_code
        post :check_name
        get :regist_succeed
      end
    end

    scope :shopping_cart do
      get :goods, to: 'shopping_cart#goods'
      post :update_item, to: 'shopping_cart#update_item'
      post :remove, to: 'shopping_cart#remove'
      post :remove_selected, to: 'shopping_cart#remove_selected'
      get :confirm, to: 'shopping_cart#confirm'
    end
    get :orders, to: 'orders#index'
    post :orders, to: 'orders#index'
    
    resources :orders do 
      post :outbound_msg
    end
    

  end  
  post '/mobile/orders/handle_alipay_notify' => 'mobile/orders#handle_alipay_notify'
  
  scope :jabber do
    post :prebind, to: 'jabber#prebind'
  end

  # 买手后台系统
  namespace :delivery do
    root to: 'index#dashboard'

    get 'login', to: 'sessions#new', as: 'login'    
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resources :materials, only: [:create]

    resources :inbounds do
      member do
        get :query
      end
    end

    resources :orders do
      member do
        post :outbound       
        post :check_prepare_products 
        post :notify_carriage
        post :notify_tax        
      end
    end

    resources :outbounds do 
      member do
        get :query                        
      end                
    end

    resources :live_shows do
      member do        
        get :open
        get :close
        post :clearing_price
        get :shopping_list        
      end

      resources :products, shallow: true
      resources :messages, shallow: true
    end
  end

  get 'costco' => 'delivery/live_shows#preview_page'  
  get 'fresh' => 'delivery/live_shows#fresh_page'
    
  # 运维后台
  namespace :cpanel do
    root to: 'live_shows#index'

    scope :faqs do
      get '1' => 'faqs#faq1'      
      get '2' => 'faqs#faq2'      
      get '3' => 'faqs#faq3'      
    end

    scope :trailer do
      get 'costco' => 'trailers#costco'      
      get 'next' => 'trailers#next'
    end

    resources :live_shows do
      member do
        get :products
        post :products
        get :close        
      end
      get :choose_material
    end

    resources :users

    resources :products do
      member do
        post :publish
      end
    end

    resources :materials, only: [:create]

    resources :orders do
      resources :items, only: [:index]
    end
  end
end

app/models/product.rb
require 'xmpp4r'
require 'xmpp4r/muc/helper/simplemucclient'

class Product < ActiveRecord::Base
  include PrimaryKeySecurity
  include Jabber
  include ReadableStatus

  has_and_belongs_to_many :materials, join_table: :product_materials
  has_many :product_materials
  belongs_to :live_show
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :skus
  has_many :specifications, class_name: "ProductSpecification", foreign_key: 'product_id'

  accepts_nested_attributes_for :specifications, reject_if: :reject_specifications, allow_destroy: true
  def reject_specifications attributed
    attributed['name'].blank? or attributed['value'].blank?
  end

  validates_length_of :description, maximum: 100, allow_blank: true 
  validates_presence_of :name_en, :price, :currency, :weight, :weight_unit
  validates_numericality_of :price, greater_than: 0
  validates_inclusion_of :currency, in: %w( Dollar RMB )
  validates_inclusion_of :weight_unit, in: %w( kg lb oz )

  enum status: [ :draft, :previewing, :published, :locked ]

  scope :published, -> { where(status: Product.statuses[:published]) }

  attr_accessor :props

  # store :content, accessors: [:specifications]
  store :content

  CURRENCIES = %w( Dollar RMB )
  WEIGHT_UNITS = %w( kg lb oz )

  def picture_ids
    @picture_ids || self.product_materials.order('created_at desc').map(&:material_id).join(",")
  end

  def picture_ids=(new_ids)
    @picture_ids = new_ids
  end

  # !!!!临时方法
  before_validation do
    if self.author_id.blank?
      self.author_id = User.first.id
    end
  end

  before_save do
    self.clearing_price = (price.to_f * live_show.exchange_rate.to_f).ceil
    self.clearing_currency = 'RMB'
    if self.name_cn.blank?
      self.name_cn = self.description
    end
  end

  def cover
    Material.find_by id: cover_id
  end

  # 可能有问题，待测试
  def default_sku
    skus.each do |sku|
      return sku if sku.prop.blank?        
    end

    skus.create!
  end

  # 这里有点乱
  def find_or_create_sku_by!(specification_str)
    specification = {}

    # 这是新增的产品规格表
    h = {}
    specifications.each do |spec|
      h[spec.name] = spec.value
    end

    specification_str.force_encoding(Encoding::UTF_8).split(/,|，/).each do |v|
      (content["specifications"] || h).each_pair do |s_name, s_value|
        if s_value.split(/,|，/).include?(v)
          specification[s_name] = v
        end
      end
    end
  
    skus.each do |sku|
      if sku.prop.stringify_keys == specification.stringify_keys
        return sku
      end
    end

    if specification.blank?
      return default_sku
    end
    
    sku = skus.build 
    sku.prop = specification
    sku.save!
    return sku
  end

  def add_to_cart_of(user, specification_str, quantity)
    sku = find_or_create_sku_by! specification_str
    sku.add_to_cart_of user, quantity
  end

  # def publish!
  #   body = ActiveRecord::Base::Message.g_product_cell self
  #   jid = author.jid_bind('web')    
  #   Jabber::debug = true
  #   client = Jabber::Reliable::Connection.new(jid, max_retry: 10, retry_sleep: 1)
  #   muc = Jabber::MUC::MUCClient.new(client)
  #   client.connect
  #   client.auth(author.ejabberd_password)
  #   muc.join("#{live_show.room_jid}/#{author.name}")
  #   msg = Jabber::Message.new live_show.room_jid, body
  #   muc.send msg
  #   self.update_attribute(:published_at, Time.now)              
  # end

  def publish!
    body = ::Message.g_product_cell self
    message = Jabber::Message.new live_show.room_jid, body
    message.set_type(:groupchat)
    mid = Array(0..99).sample + Random.rand(9999999)
    message.set_id mid
    p live_show.client
    live_show.client.send message
  end

  def carriage
    w = self.weight.to_f
    case self.weight_unit
    when 'oz'
      w = (w * 28.34952313).ceil
    when 'lb'
      w = (w * 453.59237).ceil
    when 'kg'
      w = (w * 1000).ceil
    end     

    if w == 0
      "无法估算此产品运费"
    elsif w < 500
      "30元"
    elsif w % 100 > 0
      "#{(w / 100.0).ceil * 6}元"
    else
      "#{w / 100.0 * 6}元"
    end
  end
end

app/controllers/cpanel/application_controller.rb
class Cpanel::ApplicationController < ApplicationController
  layout 'cpanel'
  before_action :login_required, :admin_required

  private

  def admin_required
    raise AccessDenied unless current_user.admin?
  end   
end

app/controllers/cpanel/faqs_controller.rb
class Cpanel::FaqsController < Cpanel::ApplicationController
	skip_before_action :login_required, :admin_required
	layout false

  def faq1   
  end
  
  def faq2
  end

  def faq3   
  end    

end

app/controllers/cpanel/items_controller.rb
class Cpanel::ItemsController < Cpanel::ApplicationController
  def index
    @order = Order.find params[:order_id]
    @items = @order.order_items.order('created_at DESC')
  end
end

app/controllers/cpanel/live_shows_controller.rb
class Cpanel::LiveShowsController < Cpanel::ApplicationController
  skip_before_action :login_required, only: :orders
  skip_before_action :admin_required, only: :orders
  before_action :find_live_show, only: [:show, :products, :orders, :edit, :update, :close]

  def index
    @live_shows = LiveShow.order('created_at DESC')
  end

  def show  
    @products = @live_show.products.order('created_at DESC')
    
    @orders = @live_show.orders.order('created_at DESC, user_id DESC').includes(:user).includes(:order_items)  

    @order_items = @live_show.order_items.select("*, sum(quantity) as quantity").joins(:order).where('orders.status = 3').group("order_items.sku_id")
  end

  def products
    @products = @live_show.products.order('created_at DESC')
    render layout: false
  end

  def new
    @live_show = LiveShow.new
  end

  def create
    @live_show = LiveShow.new live_show_params
    @live_show.generate_secure_id!
    @live_show.user_id = current_user.id

    if @live_show.save
      redirect_to cpanel_live_shows_path
    else
      render :new
    end
  end

  def edit        
  end

  def update
    @live_show.update_attributes(live_show_params)
    redirect_to cpanel_live_shows_path
  end

  def close
    @live_show.update_attributes!({ :closed => true })
    redirect_to cpanel_live_shows_path
  end

  def choose_material
    @materials = Material.where(live_show_id: params[:live_show_id])
                         .where(material_type: %w(jpeg jpg png gif))   
    render :layout => false
  end
  
  private

  def find_live_show
    @live_show = LiveShow.find params[:id]
  end

  def live_show_params
    params.require(:live_show).permit(
      :subject, :description, :preview, 
      :start_time, :close_time,
      :html_url,
      :countdown, :exchage_rate
    )
  end
end

app/controllers/cpanel/materials_controller.rb
class Cpanel::MaterialsController < Cpanel::ApplicationController
  def create
    material = current_user.materials.build
    material.live_show_id = params[:live_show_id]
    material.material_type = params[:material].content_type.split('/').last.downcase
    material.resource = params[:material]
    state = material.save

    render json: { success: state, material: material }
  end
end

app/controllers/cpanel/orders_controller.rb
class Cpanel::OrdersController < Cpanel::ApplicationController
  def index
    @orders = Order.order('created_at DESC')
  end
end

app/controllers/cpanel/products_controller.rb
class Cpanel::ProductsController < Cpanel::ApplicationController
  def index
  end

  def show
    @product = Product.find params[:id]
    render layout: false
  end

  def new
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        material_ids = product_params[:picture_ids].split(',')
        materials = Material.where(id: material_ids)
        price = product_params.delete(:price).to_f
        
        @product = current_user.products.build product_params
        @product.price = price
        @product.cover_id = material_ids.first
        @product.materials = materials
        @product.content[:specifications] = @product.props
        @product.save!   
      end

      render json: { success: true, product: @product }
    rescue => e
      render json: { success: false }
    end
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    begin
      Product.transaction do
        material_ids = params[:picture_ids].split(',')
        materials = Material.where(id: material_ids)
        
        @product.materials = materials
        @product.update_attributes! product_params
        redirect_to cpanel_live_show_path(@product.live_show_id), notice: "Update product succeed."
      end
    rescue => e
      render :edit
    end
  end

  def publish
    @product = Product.find params[:id]
    @product.published!

    render json: @product
  end

  private

  def product_params
    # params.require(:product).permit(
    #   :props,
    #   :live_show_id, :name_en, :name_cn, :price, :currency, :status,
    #   :description, :tax_rate, :brand_cn, :brand_en, :picture_ids
    # )
    params.require(:product).permit!
  end
end

app/controllers/cpanel/trailers_controller.rb
class Cpanel::TrailersController < Cpanel::ApplicationController
	layout false

  skip_before_action :login_required
  skip_before_action :admin_required
	
  def costco    
  end

  def next
  end

end

app/controllers/cpanel/users_controller.rb
class Cpanel::UsersController < Cpanel::ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/delivery/products_controller.rb
class Delivery::ProductsController < Delivery::ApplicationController
  before_action :admin_required  
  before_action :find_live_show, only: [:new, :create, :edit, :update]

  def index
  end

  def new
    @product = @live_show.products.build
    find_materials
    (2 -  @product.specifications.size).times do
      @product.specifications.build
    end    
  end

  def create
    ActiveRecord::Base.transaction do
      @product = @live_show.products.build product_params
      @product.author_id = @current_admin.id
      set_materials
      set_cover

      if @product.save
        publish_product!
        redirect_to delivery_live_show_path(@live_show)
      else
        (2 -  @product.specifications.size).times do
          @product.specifications.build
        end
        render :new
      end
    end
  end

  def edit
    @product = Product.find params[:id]
    find_materials
    (2 -  @product.specifications.size).times do
      @product.specifications.build
    end     
  end

  def update
    Product.transaction do
      @product = Product.find params[:id]

      if @product.update_attributes(product_params)
        set_materials
        set_cover
        publish_product!
        redirect_to delivery_live_show_path(@live_show)
      else
        (2 -  @product.specifications.size).times do
          @product.specifications.build
        end        
        render :edit 
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :id, :cover_id,
      :name_en, :description, :price, :weight,
      :weight_unit, :live_show_id,
      :picture_ids, :status, specifications_attributes: [:id, :name, :value]
    )
  end

  def find_live_show
    @live_show = LiveShow.find params[:live_show_id]
  end

  def find_materials
    @materials = Material.where(id: @product.picture_ids.split(",")).order('created_at desc')
  end

  def set_materials
    find_materials
    @product.materials = @materials
  end

  def set_cover
    if @product.cover_id.blank?
      @product.cover_id = @materials.first.try(:id)
    end    
  end

  def publish_product!
    if @product.published_at.blank? and @product.published?
      @product.publish! 
    end    
  end
end

app/helpers/delivery/products_helper.rb
module Delivery
  module ProductsHelper
    def status_tag product
      klass = "label"

      case product.status
      when "draft", "locked"
        klass << " label-default"
      when "previewing"
        klass << " label-info"
      when "published"
        klass << " label-success"
      end
          
      %Q(<span class="#{klass}">#{product.readable_status}</span>).html_safe
    end
  end
end

app/views/cpanel/products/create.js.erb
<%- if @product.errors.empty? %>
  $('.postProduct').button('reset');
  $('.message-box textarea').val('<%= @product.id %>');
  $('#product').addClass('hide');
  $('#reply').removeClass('hide').show();
<% end -%>

app/views/cpanel/products/edit.html.slim
= javascript_include_tag 'materials'
= stylesheet_link_tag 'chat'

.bs-docs-section
  .page-header.clearfix
    .pull-left Edit Product
    .pull-right
  .main.clearfix.product-form#Products
    .input-groups.pull-left
      = form_for @product, url: cpanel_product_path(@product) do |f|
        = render 'share/form_error_messages', form: f

        .form-group
          = f.text_field :name_en, placeholder: 'Product EN Name', required: true, class: 'form-control'
        .form-group
          = f.text_area :description, placeholder: 'Description', class: 'form-control'        
        .form-group
          = f.text_field :name_cn, placeholder: 'Product CN Name', required: true, class: 'form-control'
        .form-group
          = f.number_field :price, placeholder: 'Price', required: true, class: 'form-control'
        .form-group
          .input-group
            .input-group-addon Currency
            = f.text_field :currency, placeholder: 'Dollar', disabled: true, class: 'form-control'
        .form-group
          = f.number_field :tax_rate, placeholder: 'Tax Rate', class: 'form-control'
        .form-group
          = f.text_field :brand_en, placeholder: 'Brand EN Name', class: 'form-control'
        .form-group
          = f.text_field :brand_cn, placeholder: 'Brand CN Name', class: 'form-control'
        - (@product.content[:specifications] || {}).each_pair do |k, v|
          .form-group.property.clearfix
            input.name.form-control.pull-left type="text" placeholder="eg: Color" name="properties[][name]" value=k
            input.value.form-control.pull-left type="text" placeholder="Red,Yellow,Black" name="properties[][value]" value=v  

        .form-group
          = hidden_field_tag :picture_ids, @product.materials.map(&:id).join(',')
          = hidden_field_tag :live_show_id, @product.live_show_id
          button.btn.btn-primary.btn-lg.postProduct type="submit" data-loading-text="Loading..." Submit
    .pull-left.pictures.ml-20
      a#choose_uploaded_pic.btn.btn-primary.btn-xs href="javascript:;" live-show-id="#{@product.live_show_id}" 
        i.fa.fa-cloud
        span.ml-2 Choose uploaded pictures

      = file_field_tag 'material', id: 'product_picture', class: 'mb-30 mt-30', multiple: true

      .picture-lists.clearfix
        - @product.materials.each do |m|
          .pic id="#{m.id}"
            .remove
            = image_tag m.resource_url, size: '80x80', class:'img-thumbnail'

javascript:
  $(function () {
    $('#product_name_en').focus(function () {
      $(this).val($('#product_description').val());
    });

    $('form.edit_product').submit(function () {
      var name_en = $.trim($('#product_name_en').val());
      var price = $.trim($('#product_price').val());
      var picture_ids = $.trim($('#picture_ids').val());
      var description = $.trim($('#product_description').val());

      if (name_en.length == 0) {
        alert('Product name cannot be blank');
        return false;
      }

      if (price.length == 0) {
        alert('Product price cannot be blank');
        return false;
      }

      if (description.length == 0) {
        alert('Product description cannot be blank');
        return false;
      }

      if (picture_ids.length == 0) {
        alert('Please upload one picture at least');
        return false;
      }

      return true;
    });
  });

app/views/cpanel/products/show.html.slim
.panel.panel-default
  .panel-heading.clearfix
    .pull-left
      a href="#"= @product.name_en
      p.description style="font-size:12px; color: #999; margin-bottom:0px;"= @product.description
    .pull-right
      .dollar.price ="$#{@product.price}"
      .rmb.price= "￥#{@product.clearing_price}"
  .panel-body
    = image_tag @product.cover.resource_url